package pojos;
// Generated 11-sep-2018 10:00:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer id;
     private String usuario;
     private String contrasena;
     private String nombres;
     private String apellidos;
     private String tipoCuenta;
     private Set auditoriacuentas = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(String usuario, String contrasena, String nombres, String apellidos, String tipoCuenta) {
        this.usuario = usuario;
        this.contrasena = contrasena;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.tipoCuenta = tipoCuenta;
    }
    public Cuenta(String usuario, String contrasena, String nombres, String apellidos, String tipoCuenta, Set auditoriacuentas) {
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tipoCuenta = tipoCuenta;
       this.auditoriacuentas = auditoriacuentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public Set getAuditoriacuentas() {
        return this.auditoriacuentas;
    }
    
    public void setAuditoriacuentas(Set auditoriacuentas) {
        this.auditoriacuentas = auditoriacuentas;
    }




}


