package pojos;
// Generated 11-sep-2018 10:00:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private Integer id;
     private String codigo;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String nombres;
     private Date fechaNacimiento;
     private String ciudad;
     private String provincia;
     private String pais;
     private String graduacionUni;
     private String tituloDe;
     private String inscripcionSanitaria;
     private String libro;
     private String folio;
     private String lugarGrad;
     private Date fehaGrad;
     private String especialidad;
     private String universidadEsp;
     private Date fechaEsp;
     private String medicaturaRural;
     private Date fechaRural;
     private String estadoCivil;
     private String nombresConyuge;
     private String lugarResidencia;
     private String direccionResidencia;
     private String telfResidencia;
     private String direccionConsultorio;
     private String telfConsultorio;
     private String email;
     private String telfCelular;
     private String cedula;
     private String grupoSanguineo;
     private Date fechaAfiliacion;
     private String lugarAfiliacion;
     private byte[] fotoAsociado;
     private String estadoSocio;
     private Set auditoriacuentas = new HashSet(0);

    public Socio() {
    }

	
    public Socio(String codigo, String apellidoPaterno, String apellidoMaterno, String nombres, Date fechaNacimiento, String graduacionUni, String tituloDe, String inscripcionSanitaria, String lugarGrad, Date fehaGrad, String medicaturaRural, Date fechaRural, String estadoCivil, String email, String telfCelular, String cedula, String grupoSanguineo, Date fechaAfiliacion, String lugarAfiliacion) {
        this.codigo = codigo;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.nombres = nombres;
        this.fechaNacimiento = fechaNacimiento;
        this.graduacionUni = graduacionUni;
        this.tituloDe = tituloDe;
        this.inscripcionSanitaria = inscripcionSanitaria;
        this.lugarGrad = lugarGrad;
        this.fehaGrad = fehaGrad;
        this.medicaturaRural = medicaturaRural;
        this.fechaRural = fechaRural;
        this.estadoCivil = estadoCivil;
        this.email = email;
        this.telfCelular = telfCelular;
        this.cedula = cedula;
        this.grupoSanguineo = grupoSanguineo;
        this.fechaAfiliacion = fechaAfiliacion;
        this.lugarAfiliacion = lugarAfiliacion;
    }
    public Socio(String codigo, String apellidoPaterno, String apellidoMaterno, String nombres, Date fechaNacimiento, String ciudad, String provincia, String pais, String graduacionUni, String tituloDe, String inscripcionSanitaria, String libro, String folio, String lugarGrad, Date fehaGrad, String especialidad, String universidadEsp, Date fechaEsp, String medicaturaRural, Date fechaRural, String estadoCivil, String nombresConyuge, String lugarResidencia, String direccionResidencia, String telfResidencia, String direccionConsultorio, String telfConsultorio, String email, String telfCelular, String cedula, String grupoSanguineo, Date fechaAfiliacion, String lugarAfiliacion, byte[] fotoAsociado, String estadoSocio, Set auditoriacuentas) {
       this.codigo = codigo;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.nombres = nombres;
       this.fechaNacimiento = fechaNacimiento;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.pais = pais;
       this.graduacionUni = graduacionUni;
       this.tituloDe = tituloDe;
       this.inscripcionSanitaria = inscripcionSanitaria;
       this.libro = libro;
       this.folio = folio;
       this.lugarGrad = lugarGrad;
       this.fehaGrad = fehaGrad;
       this.especialidad = especialidad;
       this.universidadEsp = universidadEsp;
       this.fechaEsp = fechaEsp;
       this.medicaturaRural = medicaturaRural;
       this.fechaRural = fechaRural;
       this.estadoCivil = estadoCivil;
       this.nombresConyuge = nombresConyuge;
       this.lugarResidencia = lugarResidencia;
       this.direccionResidencia = direccionResidencia;
       this.telfResidencia = telfResidencia;
       this.direccionConsultorio = direccionConsultorio;
       this.telfConsultorio = telfConsultorio;
       this.email = email;
       this.telfCelular = telfCelular;
       this.cedula = cedula;
       this.grupoSanguineo = grupoSanguineo;
       this.fechaAfiliacion = fechaAfiliacion;
       this.lugarAfiliacion = lugarAfiliacion;
       this.fotoAsociado = fotoAsociado;
       this.estadoSocio = estadoSocio;
       this.auditoriacuentas = auditoriacuentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getGraduacionUni() {
        return this.graduacionUni;
    }
    
    public void setGraduacionUni(String graduacionUni) {
        this.graduacionUni = graduacionUni;
    }
    public String getTituloDe() {
        return this.tituloDe;
    }
    
    public void setTituloDe(String tituloDe) {
        this.tituloDe = tituloDe;
    }
    public String getInscripcionSanitaria() {
        return this.inscripcionSanitaria;
    }
    
    public void setInscripcionSanitaria(String inscripcionSanitaria) {
        this.inscripcionSanitaria = inscripcionSanitaria;
    }
    public String getLibro() {
        return this.libro;
    }
    
    public void setLibro(String libro) {
        this.libro = libro;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getLugarGrad() {
        return this.lugarGrad;
    }
    
    public void setLugarGrad(String lugarGrad) {
        this.lugarGrad = lugarGrad;
    }
    public Date getFehaGrad() {
        return this.fehaGrad;
    }
    
    public void setFehaGrad(Date fehaGrad) {
        this.fehaGrad = fehaGrad;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public String getUniversidadEsp() {
        return this.universidadEsp;
    }
    
    public void setUniversidadEsp(String universidadEsp) {
        this.universidadEsp = universidadEsp;
    }
    public Date getFechaEsp() {
        return this.fechaEsp;
    }
    
    public void setFechaEsp(Date fechaEsp) {
        this.fechaEsp = fechaEsp;
    }
    public String getMedicaturaRural() {
        return this.medicaturaRural;
    }
    
    public void setMedicaturaRural(String medicaturaRural) {
        this.medicaturaRural = medicaturaRural;
    }
    public Date getFechaRural() {
        return this.fechaRural;
    }
    
    public void setFechaRural(Date fechaRural) {
        this.fechaRural = fechaRural;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNombresConyuge() {
        return this.nombresConyuge;
    }
    
    public void setNombresConyuge(String nombresConyuge) {
        this.nombresConyuge = nombresConyuge;
    }
    public String getLugarResidencia() {
        return this.lugarResidencia;
    }
    
    public void setLugarResidencia(String lugarResidencia) {
        this.lugarResidencia = lugarResidencia;
    }
    public String getDireccionResidencia() {
        return this.direccionResidencia;
    }
    
    public void setDireccionResidencia(String direccionResidencia) {
        this.direccionResidencia = direccionResidencia;
    }
    public String getTelfResidencia() {
        return this.telfResidencia;
    }
    
    public void setTelfResidencia(String telfResidencia) {
        this.telfResidencia = telfResidencia;
    }
    public String getDireccionConsultorio() {
        return this.direccionConsultorio;
    }
    
    public void setDireccionConsultorio(String direccionConsultorio) {
        this.direccionConsultorio = direccionConsultorio;
    }
    public String getTelfConsultorio() {
        return this.telfConsultorio;
    }
    
    public void setTelfConsultorio(String telfConsultorio) {
        this.telfConsultorio = telfConsultorio;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelfCelular() {
        return this.telfCelular;
    }
    
    public void setTelfCelular(String telfCelular) {
        this.telfCelular = telfCelular;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getGrupoSanguineo() {
        return this.grupoSanguineo;
    }
    
    public void setGrupoSanguineo(String grupoSanguineo) {
        this.grupoSanguineo = grupoSanguineo;
    }
    public Date getFechaAfiliacion() {
        return this.fechaAfiliacion;
    }
    
    public void setFechaAfiliacion(Date fechaAfiliacion) {
        this.fechaAfiliacion = fechaAfiliacion;
    }
    public String getLugarAfiliacion() {
        return this.lugarAfiliacion;
    }
    
    public void setLugarAfiliacion(String lugarAfiliacion) {
        this.lugarAfiliacion = lugarAfiliacion;
    }
    public byte[] getFotoAsociado() {
        return this.fotoAsociado;
    }
    
    public void setFotoAsociado(byte[] fotoAsociado) {
        this.fotoAsociado = fotoAsociado;
    }
    public String getEstadoSocio() {
        return this.estadoSocio;
    }
    
    public void setEstadoSocio(String estadoSocio) {
        this.estadoSocio = estadoSocio;
    }
    public Set getAuditoriacuentas() {
        return this.auditoriacuentas;
    }
    
    public void setAuditoriacuentas(Set auditoriacuentas) {
        this.auditoriacuentas = auditoriacuentas;
    }




}


