/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiomedicos;

import eventos.hCuenta;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import herramientas.Herramientas;
import static herramientas.Herramientas.EncolumnarComponentes;
import herramientas.IdiomaESP;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import pojos.Cuenta;

/**
 *
 * @author PC
 */
public class jiMiCuenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form jiMiCuenta
     */
    private Cuenta cuenta;
    public jiMiCuenta(String _titulo,int _ID) {
        initComponents();
        cuenta = hCuenta.obtenerCuenta(_ID);
        this.setTitle(_titulo);
        this.setClosable(true);
        this.setIconifiable(true);
        jtxtNombres.setText(cuenta.getNombres());
        jtxtApellidos.setText(cuenta.getApellidos());
        jtxtCuenta.setText(cuenta.getUsuario());
        jPasword.setText(cuenta.getContrasena());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasword = new javax.swing.JPasswordField();
        jbActualizar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        jLabel1.setText(IdiomaESP.lbNombres);

        jtxtNombres.setPreferredSize(new java.awt.Dimension(150, 20));
        jtxtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombresActionPerformed(evt);
            }
        });

        jLabel2.setText(IdiomaESP.lbApellidos);

        jtxtApellidos.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel3.setText(IdiomaESP.lbUsuario);

        jtxtCuenta.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel4.setText(IdiomaESP.lbContrasena);

        jbActualizar.setText(IdiomaESP.btActualizar);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbCancelar.setText(IdiomaESP.btCancelar);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jbActualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jPasword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.cuenta=null;
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jtxtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        if(jtxtNombres.getText().isEmpty() || jtxtApellidos.getText().isEmpty() || jtxtCuenta.getText().isEmpty() || jPasword.getPassword().length==0){
            herramientas.Herramientas.MensajeAdv(IdiomaESP.mErMiCuentaCampoVacio);
        }
        else{
            cuenta.setNombres(jtxtNombres.getText());
            cuenta.setApellidos(jtxtApellidos.getText());
            cuenta.setUsuario(jtxtCuenta.getText());
            cuenta.setContrasena(new String(jPasword.getPassword()));
            if(hCuenta.editarCuenta(cuenta)){
                herramientas.Herramientas.MensajeInfo(IdiomaESP.mMiCuentaActualizada);
            }
            else{
                herramientas.Herramientas.MensajeErr(IdiomaESP.mErMiCuentaGuardar);
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasword;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtCuenta;
    private javax.swing.JTextField jtxtNombres;
    // End of variables declaration//GEN-END:variables
}
