/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiomedicos;

import eventos.hCuenta;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import herramientas.IdiomaESP;
import pojos.Cuenta;

/**
 *
 * @author PC
 */
public class jiRecuperarContraseña extends javax.swing.JInternalFrame {

    /**
     * Creates new form jiRecuperarContraseña
     */
    private Cuenta cuenta;

    public jiRecuperarContraseña(String _titulo) {
        initComponents();
        this.setTitle(_titulo);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtContrasena = new javax.swing.JTextField();
        jbActualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbCancelar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();

        jLabel1.setText(IdiomaESP.lbUsuario);

        jLabel2.setText(IdiomaESP.lbContrasena);

        jtxtContrasena.setEnabled(false);

        jbActualizar.setText(IdiomaESP.btActualizar);
        jbActualizar.setEnabled(false);
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbCancelar.setText(IdiomaESP.btCancelar);
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        btBuscar.setText(IdiomaESP.btBuscar);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtCuenta)
                            .addComponent(jtxtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jbActualizar)
                        .addGap(27, 27, 27)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        if (jtxtContrasena.getText().isEmpty()) {
            herramientas.Herramientas.MensajeAdv(IdiomaESP.mErMiCuentaCampoVacio);
        } else {
            cuenta.setContrasena(jtxtContrasena.getText());
            if (hCuenta.editarCuenta(cuenta)) {
                herramientas.Herramientas.MensajeInfo(IdiomaESP.mMiCuentaActualizada);
                jtxtCuenta.setEnabled(true);;
                jtxtCuenta.setText("");
                jtxtContrasena.setText("");
                jtxtContrasena.setEnabled(false);
                jbActualizar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
        // sdfsd
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        cuenta = hCuenta.buscarCuenta(this.jtxtCuenta.getText());
        if (cuenta == null) {
            herramientas.Herramientas.MensajeErr(IdiomaESP.mNoCuentaEncontrada(jtxtCuenta.getText()), IdiomaESP.tNoCuentaEncontrada);
        } else {
            if (cuenta.getTipoCuenta().equals("a") || cuenta.getTipoCuenta().equals("s")) {
                herramientas.Herramientas.MensajeErr(IdiomaESP.mNoPrivilegioCuenta, IdiomaESP.tNoPrivilegioCuenta);
            } else {
                jtxtContrasena.setEnabled(true);
                jbActualizar.setEnabled(true);
                jtxtCuenta.setEnabled(!false);
            }
        }

    }//GEN-LAST:event_btBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JTextField jtxtContrasena;
    private javax.swing.JTextField jtxtCuenta;
    // End of variables declaration//GEN-END:variables
}
